# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 471)
        MainWindow.setStyleSheet("background-color: rgb(222, 229, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Browse.setGeometry(QtCore.QRect(670, 10, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_Browse.setFont(font)
        self.btn_Browse.setAutoFillBackground(False)
        self.btn_Browse.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}\n"
"")
        self.btn_Browse.setCheckable(False)
        self.btn_Browse.setChecked(False)
        self.btn_Browse.setObjectName("btn_Browse")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setEnabled(True)
        self.filename.setGeometry(QtCore.QRect(10, 10, 651, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.filename.setFont(font)
        self.filename.setStyleSheet("QLineEdit {\n"
"    border-style:none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.filename.setObjectName("filename")
        self.diagButton = QtWidgets.QPushButton(self.centralwidget)
        self.diagButton.setEnabled(True)
        self.diagButton.setGeometry(QtCore.QRect(670, 310, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.diagButton.setFont(font)
        self.diagButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.diagButton.setObjectName("diagButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 651, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(113, 14, 205);\n"
"    text-align: center;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setEnabled(True)
        self.trainButton.setGeometry(QtCore.QRect(670, 140, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.trainButton.setFont(font)
        self.trainButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.trainButton.setObjectName("trainButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 100, 241, 41))
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: rgb(113, 14, 205);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 260, 241, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(113, 14, 205);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 150, 651, 291))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setEnabled(True)
        self.saveButton.setGeometry(QtCore.QRect(10, 230, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.diapLine1 = QtWidgets.QLineEdit(self.frame)
        self.diapLine1.setGeometry(QtCore.QRect(190, 160, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.diapLine1.setFont(font)
        self.diapLine1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.diapLine1.setObjectName("diapLine1")
        self.diseaseLine = QtWidgets.QLineEdit(self.frame)
        self.diseaseLine.setGeometry(QtCore.QRect(160, 90, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.diseaseLine.setFont(font)
        self.diseaseLine.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.diseaseLine.setObjectName("diseaseLine")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.diesaseLabel = QtWidgets.QLabel(self.frame)
        self.diesaseLabel.setGeometry(QtCore.QRect(130, 90, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.diesaseLabel.setFont(font)
        self.diesaseLabel.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.diesaseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.diesaseLabel.setObjectName("diesaseLabel")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(400, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.diapLine2 = QtWidgets.QLineEdit(self.frame)
        self.diapLine2.setGeometry(QtCore.QRect(460, 160, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.diapLine2.setFont(font)
        self.diapLine2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.diapLine2.setObjectName("diapLine2")
        self.numDiesases = QtWidgets.QSpinBox(self.frame)
        self.numDiesases.setEnabled(True)
        self.numDiesases.setGeometry(QtCore.QRect(250, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.numDiesases.setFont(font)
        self.numDiesases.setObjectName("numDiesases")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 60, 651, 16))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.diesaseLabel_2 = QtWidgets.QLabel(self.frame)
        self.diesaseLabel_2.setGeometry(QtCore.QRect(0, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.diesaseLabel_2.setFont(font)
        self.diesaseLabel_2.setStyleSheet("")
        self.diesaseLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.diesaseLabel_2.setObjectName("diesaseLabel_2")
        self.diesaseLabel_3 = QtWidgets.QLabel(self.frame)
        self.diesaseLabel_3.setGeometry(QtCore.QRect(0, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.diesaseLabel_3.setFont(font)
        self.diesaseLabel_3.setStyleSheet("")
        self.diesaseLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.diesaseLabel_3.setObjectName("diesaseLabel_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 290, 241, 21))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgb(113, 14, 205);\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame.raise_()
        self.btn_Browse.raise_()
        self.diagButton.raise_()
        self.label.raise_()
        self.trainButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.filename.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Browse.setText(_translate("MainWindow", "найти .XLS файл"))
        self.filename.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.diagButton.setText(_translate("MainWindow", "Диагнозировать"))
        self.label.setText(_translate("MainWindow", "Необходимые данные"))
        self.trainButton.setText(_translate("MainWindow", "Обучить"))
        self.label_2.setText(_translate("MainWindow", "нажмите сюда что бы обучить"))
        self.label_3.setText(_translate("MainWindow", "нажмите сюда что бы "))
        self.saveButton.setText(_translate("MainWindow", "сохранить данные в БД"))
        self.label_5.setText(_translate("MainWindow", "Начало диапазона"))
        self.diesaseLabel.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "до-"))
        self.label_7.setText(_translate("MainWindow", "Количество болезней"))
        self.diesaseLabel_2.setText(_translate("MainWindow", "болезни №"))
        self.diesaseLabel_3.setText(_translate("MainWindow", "Название"))
        self.label_4.setText(_translate("MainWindow", "диагназировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
